spring.application.name=skullking-backend

# Habilitar la consola web de H2
spring.h2.console.enabled=true

# Ruta de acceso a la consola en el navegador (por defecto /h2-console)
spring.h2.console.path=/h2-console

# Configuración de la base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=